name: Urgency Service CI

on:
  workflow_dispatch:
      #Trigger the workflow on push from the main branch
  push:
    branches:
      - main

jobs:
  #Test's jobs
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lauching unit testing job"
        uses: actions/checkout@v3
      - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: '11'
      #Run Tests
      - name: Run Tests
        run: mvn -B test