name: Urgency Service CI

on: [push]

jobs:
  #Test jobs
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copy of the repo on the runner
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run unit tests
        run: mvn clean test
  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copy of the repo on the runner
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run integration tests
        run: mvn failsafe:integration-test

  #Build jobs
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copy of the repo on the runner
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Upload artifact
        run: mkdir staging && cp target/*.jar staging
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging